# Generated by Django 5.0.1 on 2024-02-11 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('G', 'Genderless'), ('M', 'Men'), ('W', 'Women'), ('A', 'Accessories')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('T', 'Tops'), ('B', 'Bottoms'), ('H', 'Headware'), ('A', 'Accessories')], default='T', max_length=1),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=150)),
                ('image_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
