# Generated by Django 5.0.1 on 2024-02-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_product_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fits_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='xs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='xxl',
            field=models.IntegerField(default=0),
        ),
    ]
