# Generated by Django 5.0.1 on 2024-03-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_category',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_subcategory',
            field=models.SlugField(default=''),
        ),
    ]
