# Generated by Django 5.0.1 on 2024-03-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_product_slug_category_product_slug_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slug_name',
        ),
    ]
