# Generated by Django 5.0.1 on 2024-03-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_slug_product_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Genderless', 'Genderless'), ('Men', 'Men'), ('Women', 'Women'), ('Accessories', 'Accessories')], default='Genderless'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Headware', 'Headware'), ('Accessories', 'Accessories')], default='Tops'),
        ),
    ]
